steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ["build", "-t", "gcr.io/corded-pivot-374409/news", "-f", "trainer.dockerfile", "."]
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/corded-pivot-374409/news"]
