steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ["build", "-t", "gcr.io/corded-pivot-374409/news", "-f", "trainer.dockerfile", "."]
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/corded-pivot-374409/news"]

    - name: 'gcr.io/cloud-builders/docker'
      args: ["build", "-t", "gcr.io/corded-pivot-374409/predictor", "-f", "predictor.dockerfile", "."]
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/corded-pivot-374409/predictor"]

    - name: 'gcr.io/cloud-builders/gcloud'
      args: ["run", "services", "update", "predictor", "--image", "gcr.io/corded-pivot-374409/predictor", "--region", "europe-west4"]
