---
name: Run tests
on:
  push:
    branches: [master, main, tests]
  pull_request:
    branches: [master, main]
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_tests.txt
      - name: Test with pytest
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          pip install pytest coverage
          pytest -v
          coverage run -m pytest tests/
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
