name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Test with pytest and generate coverage report
      run: |
        pip install pytest coverage
        coverage run -m pytest tests/ -vv
        coverage report -m
        coverage xml
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      if: always()
      continue-on-error: true
      with:
          token: ${{secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: cpu,pytest,${{ runner.os }}
          nmae: Test-coverage
          fail_ci_if_error: false
